// Mocks generated by Mockito 5.4.6 from annotations
// in lexilingo_app/test/features/progress/domain/usecases/complete_lesson_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:lexilingo_app/core/error/failures.dart' as _i5;
import 'package:lexilingo_app/features/progress/domain/entities/daily_challenge_entity.dart'
    as _i9;
import 'package:lexilingo_app/features/progress/domain/entities/streak_entity.dart'
    as _i8;
import 'package:lexilingo_app/features/progress/domain/entities/user_progress_entity.dart'
    as _i6;
import 'package:lexilingo_app/features/progress/domain/entities/weekly_progress_entity.dart'
    as _i7;
import 'package:lexilingo_app/features/progress/domain/repositories/progress_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProgressRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProgressRepository extends _i1.Mock
    implements _i3.ProgressRepository {
  MockProgressRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.ProgressStatsEntity>>
  getMyProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getMyProgress, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.ProgressStatsEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.ProgressStatsEntity>(
                    this,
                    Invocation.method(#getMyProgress, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.ProgressStatsEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CourseProgressWithUnits>>
  getCourseProgress(String? courseId) =>
      (super.noSuchMethod(
            Invocation.method(#getCourseProgress, [courseId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.CourseProgressWithUnits>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.CourseProgressWithUnits>(
                    this,
                    Invocation.method(#getCourseProgress, [courseId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.CourseProgressWithUnits>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.LessonCompletionResult>>
  completeLesson({required String? lessonId, required double? score}) =>
      (super.noSuchMethod(
            Invocation.method(#completeLesson, [], {
              #lessonId: lessonId,
              #score: score,
            }),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i6.LessonCompletionResult>
                >.value(
                  _FakeEither_0<_i5.Failure, _i6.LessonCompletionResult>(
                    this,
                    Invocation.method(#completeLesson, [], {
                      #lessonId: lessonId,
                      #score: score,
                    }),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.LessonCompletionResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, int>> getTotalXp() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalXp, []),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, int>>.value(
              _FakeEither_0<_i5.Failure, int>(
                this,
                Invocation.method(#getTotalXp, []),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, int>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.WeeklyProgressEntity>>
  getWeeklyProgress() =>
      (super.noSuchMethod(
            Invocation.method(#getWeeklyProgress, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i7.WeeklyProgressEntity>
                >.value(
                  _FakeEither_0<_i5.Failure, _i7.WeeklyProgressEntity>(
                    this,
                    Invocation.method(#getWeeklyProgress, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i7.WeeklyProgressEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.StreakEntity>> getMyStreak() =>
      (super.noSuchMethod(
            Invocation.method(#getMyStreak, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.StreakEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i8.StreakEntity>(
                    this,
                    Invocation.method(#getMyStreak, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.StreakEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.StreakUpdateResult>> updateStreak() =>
      (super.noSuchMethod(
            Invocation.method(#updateStreak, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i8.StreakUpdateResult>
                >.value(
                  _FakeEither_0<_i5.Failure, _i8.StreakUpdateResult>(
                    this,
                    Invocation.method(#updateStreak, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.StreakUpdateResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>> useStreakFreeze() =>
      (super.noSuchMethod(
            Invocation.method(#useStreakFreeze, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#useStreakFreeze, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.StreakEntity>> restoreStreak() =>
      (super.noSuchMethod(
            Invocation.method(#restoreStreak, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.StreakEntity>>.value(
                  _FakeEither_0<_i5.Failure, _i8.StreakEntity>(
                    this,
                    Invocation.method(#restoreStreak, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.StreakEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
  claimDailyReward() =>
      (super.noSuchMethod(
            Invocation.method(#claimDailyReward, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#claimDailyReward, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.DailyChallengesResponse>>
  getDailyChallenges() =>
      (super.noSuchMethod(
            Invocation.method(#getDailyChallenges, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, _i9.DailyChallengesResponse>
                >.value(
                  _FakeEither_0<_i5.Failure, _i9.DailyChallengesResponse>(
                    this,
                    Invocation.method(#getDailyChallenges, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i9.DailyChallengesResponse>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>
  claimChallengeReward(String? challengeId) =>
      (super.noSuchMethod(
            Invocation.method(#claimChallengeReward, [challengeId]),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>.value(
                  _FakeEither_0<_i5.Failure, Map<String, dynamic>>(
                    this,
                    Invocation.method(#claimChallengeReward, [challengeId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, Map<String, dynamic>>>);
}
