// Mocks generated by Mockito from annotations
// in lexilingo_app/test/features/auth/presentation/pages/login_page_navigation_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i12;
import 'dart:ui' as _i13;

import 'package:lexilingo_app/core/services/facebook_sign_in_service.dart'
    as _i10;
import 'package:lexilingo_app/core/services/google_sign_in_service.dart' as _i9;
import 'package:lexilingo_app/features/auth/domain/repositories/auth_repository.dart'
    as _i8;
import 'package:lexilingo_app/features/auth/domain/usecases/get_current_user_usecase.dart'
    as _i6;
import 'package:lexilingo_app/features/auth/domain/usecases/register_usecase.dart'
    as _i7;
import 'package:lexilingo_app/features/auth/domain/usecases/sign_in_with_email_password_usecase.dart'
    as _i4;
import 'package:lexilingo_app/features/auth/domain/usecases/sign_in_with_facebook_usecase.dart'
    as _i3;
import 'package:lexilingo_app/features/auth/domain/usecases/sign_in_with_google_usecase.dart'
    as _i2;
import 'package:lexilingo_app/features/auth/domain/usecases/sign_out_usecase.dart'
    as _i5;
import 'package:lexilingo_app/features/auth/presentation/providers/auth_provider.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSignInWithGoogleUseCase_0 extends _i1.SmartFake
    implements _i2.SignInWithGoogleUseCase {
  _FakeSignInWithGoogleUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignInWithFacebookUseCase_1 extends _i1.SmartFake
    implements _i3.SignInWithFacebookUseCase {
  _FakeSignInWithFacebookUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignInWithEmailPasswordUseCase_2 extends _i1.SmartFake
    implements _i4.SignInWithEmailPasswordUseCase {
  _FakeSignInWithEmailPasswordUseCase_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

class _FakeSignOutUseCase_3 extends _i1.SmartFake
    implements _i5.SignOutUseCase {
  _FakeSignOutUseCase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetCurrentUserUseCase_4 extends _i1.SmartFake
    implements _i6.GetCurrentUserUseCase {
  _FakeGetCurrentUserUseCase_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRegisterUseCase_5 extends _i1.SmartFake
    implements _i7.RegisterUseCase {
  _FakeRegisterUseCase_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthRepository_6 extends _i1.SmartFake
    implements _i8.AuthRepository {
  _FakeAuthRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoogleSignInService_7 extends _i1.SmartFake
    implements _i9.GoogleSignInService {
  _FakeGoogleSignInService_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFacebookSignInService_8 extends _i1.SmartFake
    implements _i10.FacebookSignInService {
  _FakeFacebookSignInService_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i11.AuthProvider {
  @override
  _i2.SignInWithGoogleUseCase get signInWithGoogleUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#signInWithGoogleUseCase),
            returnValue: _FakeSignInWithGoogleUseCase_0(
              this,
              Invocation.getter(#signInWithGoogleUseCase),
            ),
            returnValueForMissingStub: _FakeSignInWithGoogleUseCase_0(
              this,
              Invocation.getter(#signInWithGoogleUseCase),
            ),
          )
          as _i2.SignInWithGoogleUseCase);

  @override
  _i3.SignInWithFacebookUseCase get signInWithFacebookUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#signInWithFacebookUseCase),
            returnValue: _FakeSignInWithFacebookUseCase_1(
              this,
              Invocation.getter(#signInWithFacebookUseCase),
            ),
            returnValueForMissingStub: _FakeSignInWithFacebookUseCase_1(
              this,
              Invocation.getter(#signInWithFacebookUseCase),
            ),
          )
          as _i3.SignInWithFacebookUseCase);

  @override
  _i4.SignInWithEmailPasswordUseCase get signInWithEmailPasswordUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#signInWithEmailPasswordUseCase),
            returnValue: _FakeSignInWithEmailPasswordUseCase_2(
              this,
              Invocation.getter(#signInWithEmailPasswordUseCase),
            ),
            returnValueForMissingStub: _FakeSignInWithEmailPasswordUseCase_2(
              this,
              Invocation.getter(#signInWithEmailPasswordUseCase),
            ),
          )
          as _i4.SignInWithEmailPasswordUseCase);

  @override
  _i5.SignOutUseCase get signOutUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#signOutUseCase),
            returnValue: _FakeSignOutUseCase_3(
              this,
              Invocation.getter(#signOutUseCase),
            ),
            returnValueForMissingStub: _FakeSignOutUseCase_3(
              this,
              Invocation.getter(#signOutUseCase),
            ),
          )
          as _i5.SignOutUseCase);

  @override
  _i6.GetCurrentUserUseCase get getCurrentUserUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#getCurrentUserUseCase),
            returnValue: _FakeGetCurrentUserUseCase_4(
              this,
              Invocation.getter(#getCurrentUserUseCase),
            ),
            returnValueForMissingStub: _FakeGetCurrentUserUseCase_4(
              this,
              Invocation.getter(#getCurrentUserUseCase),
            ),
          )
          as _i6.GetCurrentUserUseCase);

  @override
  _i7.RegisterUseCase get registerUseCase =>
      (super.noSuchMethod(
            Invocation.getter(#registerUseCase),
            returnValue: _FakeRegisterUseCase_5(
              this,
              Invocation.getter(#registerUseCase),
            ),
            returnValueForMissingStub: _FakeRegisterUseCase_5(
              this,
              Invocation.getter(#registerUseCase),
            ),
          )
          as _i7.RegisterUseCase);

  @override
  _i8.AuthRepository get authRepository =>
      (super.noSuchMethod(
            Invocation.getter(#authRepository),
            returnValue: _FakeAuthRepository_6(
              this,
              Invocation.getter(#authRepository),
            ),
            returnValueForMissingStub: _FakeAuthRepository_6(
              this,
              Invocation.getter(#authRepository),
            ),
          )
          as _i8.AuthRepository);

  @override
  _i9.GoogleSignInService get googleSignInService =>
      (super.noSuchMethod(
            Invocation.getter(#googleSignInService),
            returnValue: _FakeGoogleSignInService_7(
              this,
              Invocation.getter(#googleSignInService),
            ),
            returnValueForMissingStub: _FakeGoogleSignInService_7(
              this,
              Invocation.getter(#googleSignInService),
            ),
          )
          as _i9.GoogleSignInService);

  @override
  _i10.FacebookSignInService get facebookSignInService =>
      (super.noSuchMethod(
            Invocation.getter(#facebookSignInService),
            returnValue: _FakeFacebookSignInService_8(
              this,
              Invocation.getter(#facebookSignInService),
            ),
            returnValueForMissingStub: _FakeFacebookSignInService_8(
              this,
              Invocation.getter(#facebookSignInService),
            ),
          )
          as _i10.FacebookSignInService);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isCheckingAuth =>
      (super.noSuchMethod(
            Invocation.getter(#isCheckingAuth),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isJustLoggedIn =>
      (super.noSuchMethod(
            Invocation.getter(#isJustLoggedIn),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(
            Invocation.getter(#hasListeners),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearJustLoggedIn() => super.noSuchMethod(
    Invocation.method(#clearJustLoggedIn, []),
    returnValueForMissingStub: null,
  );

  @override
  _i12.Future<void> refreshCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#refreshCurrentUser, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> signInWithFacebook() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithFacebook, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> signInWithEmailPassword(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailPassword, [email, password]),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<bool> requestPasswordReset(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#requestPasswordReset, [email]),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> resendVerificationEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resendVerificationEmail, [email]),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<bool> resetPassword({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [], {
              #token: token,
              #newPassword: newPassword,
            }),
            returnValue: _i12.Future<bool>.value(false),
            returnValueForMissingStub: _i12.Future<bool>.value(false),
          )
          as _i12.Future<bool>);

  @override
  _i12.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> deleteAccount() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, []),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> register({
    required String? email,
    required String? username,
    required String? password,
    String? displayName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#register, [], {
              #email: email,
              #username: username,
              #password: password,
              #displayName: displayName,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> updateProfile({String? displayName, String? avatarUrl}) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #displayName: displayName,
              #avatarUrl: avatarUrl,
            }),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  _i12.Future<void> submitOnboarding(
    Map<String, dynamic>? payload, {
    String? displayName,
    String? nativeLanguage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #submitOnboarding,
              [payload],
              {#displayName: displayName, #nativeLanguage: nativeLanguage},
            ),
            returnValue: _i12.Future<void>.value(),
            returnValueForMissingStub: _i12.Future<void>.value(),
          )
          as _i12.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i13.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
