"""add_streak_restore_and_reward

Revision ID: bd41c2120a87
Revises: game_award_idempotency
Create Date: 2026-06-16 12:34:03.334869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bd41c2120a87'
down_revision: Union[str, None] = 'game_award_idempotency'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streaks', sa.Column('previous_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('streaks', sa.Column('restores_used_this_month', sa.Integer(), server_default='0', nullable=False))
    op.add_column('streaks', sa.Column('last_restore_date', sa.Date(), nullable=True))
    op.add_column('streaks', sa.Column('last_reward_claim_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streaks', 'last_reward_claim_date')
    op.drop_column('streaks', 'last_restore_date')
    op.drop_column('streaks', 'restores_used_this_month')
    op.drop_column('streaks', 'previous_streak')
    # ### end Alembic commands ###
