"""
Seed and backfill achievements with stable slugs and badge CDN links.

This script is idempotent:
- Updates existing rows by slug (or by name for legacy rows without slug).
- Inserts missing achievements.
"""

import asyncio
from typing import Any

from sqlalchemy import func, select

from app.core.database import AsyncSessionLocal
from app.models.gamification import Achievement


BADGE_CDN_BASE = (
    "https://cdn.jsdelivr.net/gh/InfinityZero3000/"
    "LexiLingo@feature/flutter-app/assets/badges"
)


BADGE_FILES: dict[str, str] = {
    "first_steps": "common-lesson.png",
    "dedicated_learner": "common-lesson.png",
    "knowledge_seeker": "rare-lesson.png",
    "scholar": "epic-lesson.png",
    "professor": "legendary-lesson.png",
    "getting_started": "streak3.png",
    "week_warrior": "streak7.png",
    "two_weeks_strong": "streak30.png",
    "month_master": "streak30.png",
    "quarterly_champion": "streak90.png",
    "year_legend": "streak365.png",
    "word_collector": "common-vocabulary.png",
    "vocab_builder": "rare-vocabulary.png",
    "vocab_master": "epic-vocabulary.png",
    "walking_dictionary": "legendary-vocabulary.png",
    "perfectionist": "100%.png",
    "first_perfect_score": "first-perfect.png",
    "accuracy_master": "perfect-10.png",
    "flawless": "perfect-50.png",
    "quiz_champion": "quiz-champion.png",
    "course_explorer": "course-graduate.png",
    "course_champion": "course-master.png",
    "voice_beginner": "voice-starter.png",
    "voice_talent": "voice-pro.png",
    "level_25": "lv25.png",
    "level_50": "lv50.png",
    "level_100": "lv100.png",
    "level_150": "lv150.png",
    "level_200": "lv200.png",
    "level_300": "lv300.png",
    "level_500": "lv500.png",
    "night_owl": "moon.png",
    "early_bird": "early-bird.png",
    "speed_demon": "speed-demon.png",
    "grammar_guardian": "grammar-guardian.png",
    "culture_explorer": "culture-explorer.png",
    "writing_wizard": "writing-wizard.png",
    "listening_legend": "listening-legend.png",
    "social_butterfly": "social-butterfly.png",
    "conversation_champion": "conversation-champion.png",
    "feedback_friend": "feedback-friend.png",
    "challenge_crusher": "challenge-crusher.png",
    "milestone_maker": "milestone-maker.png",
    "comeback_king": "comeback-king.png",
}


def _cdn_badge_icon(slug: str) -> str | None:
    filename = BADGE_FILES.get(slug)
    if not filename:
        return None
    return f"{BADGE_CDN_BASE}/{filename}"


ACHIEVEMENT_SEED: list[dict[str, Any]] = [
    # Lessons
    {
        "slug": "first_steps",
        "name": "First Steps",
        "description": "Complete your first lesson.",
        "condition_type": "lesson_complete",
        "condition_value": 1,
        "category": "lessons",
        "rarity": "common",
        "xp_reward": 10,
        "gems_reward": 5,
        "badge_color": "#4CAF50",
        "is_hidden": False,
    },
    {
        "slug": "dedicated_learner",
        "name": "Dedicated Learner",
        "description": "Complete 10 lessons.",
        "condition_type": "lesson_complete",
        "condition_value": 10,
        "category": "lessons",
        "rarity": "common",
        "xp_reward": 30,
        "gems_reward": 15,
        "badge_color": "#8BC34A",
        "is_hidden": False,
    },
    {
        "slug": "knowledge_seeker",
        "name": "Knowledge Seeker",
        "description": "Complete 50 lessons.",
        "condition_type": "lesson_complete",
        "condition_value": 50,
        "category": "lessons",
        "rarity": "rare",
        "xp_reward": 100,
        "gems_reward": 50,
        "badge_color": "#009688",
        "is_hidden": False,
    },
    {
        "slug": "scholar",
        "name": "Scholar",
        "description": "Complete 100 lessons.",
        "condition_type": "lesson_complete",
        "condition_value": 100,
        "category": "lessons",
        "rarity": "epic",
        "xp_reward": 200,
        "gems_reward": 100,
        "badge_color": "#673AB7",
        "is_hidden": False,
    },
    {
        "slug": "professor",
        "name": "Professor",
        "description": "Complete 500 lessons.",
        "condition_type": "lesson_complete",
        "condition_value": 500,
        "category": "lessons",
        "rarity": "legendary",
        "xp_reward": 500,
        "gems_reward": 250,
        "badge_color": "#FFD700",
        "is_hidden": False,
    },
    # Streak
    {
        "slug": "getting_started",
        "name": "Getting Started",
        "description": "Maintain a 3-day streak.",
        "condition_type": "reach_streak",
        "condition_value": 3,
        "category": "streak",
        "rarity": "common",
        "xp_reward": 15,
        "gems_reward": 10,
        "badge_color": "#FF9800",
        "is_hidden": False,
    },
    {
        "slug": "week_warrior",
        "name": "Week Warrior",
        "description": "Maintain a 7-day streak.",
        "condition_type": "reach_streak",
        "condition_value": 7,
        "category": "streak",
        "rarity": "rare",
        "xp_reward": 50,
        "gems_reward": 25,
        "badge_color": "#FF5722",
        "is_hidden": False,
    },
    {
        "slug": "two_weeks_strong",
        "name": "Two Weeks Strong",
        "description": "Maintain a 14-day streak.",
        "condition_type": "reach_streak",
        "condition_value": 14,
        "category": "streak",
        "rarity": "rare",
        "xp_reward": 100,
        "gems_reward": 50,
        "badge_color": "#E91E63",
        "is_hidden": False,
    },
    {
        "slug": "month_master",
        "name": "Month Master",
        "description": "Maintain a 30-day streak.",
        "condition_type": "reach_streak",
        "condition_value": 30,
        "category": "streak",
        "rarity": "epic",
        "xp_reward": 200,
        "gems_reward": 100,
        "badge_color": "#9C27B0",
        "is_hidden": False,
    },
    {
        "slug": "quarterly_champion",
        "name": "Quarterly Champion",
        "description": "Maintain a 90-day streak.",
        "condition_type": "reach_streak",
        "condition_value": 90,
        "category": "streak",
        "rarity": "legendary",
        "xp_reward": 500,
        "gems_reward": 250,
        "badge_color": "#3F51B5",
        "is_hidden": False,
    },
    {
        "slug": "year_legend",
        "name": "Year Legend",
        "description": "Maintain a 365-day streak.",
        "condition_type": "reach_streak",
        "condition_value": 365,
        "category": "streak",
        "rarity": "legendary",
        "xp_reward": 1000,
        "gems_reward": 500,
        "badge_color": "#FFD700",
        "is_hidden": True,
    },
    # Vocabulary
    {
        "slug": "word_collector",
        "name": "Word Collector",
        "description": "Master 10 vocabulary words.",
        "condition_type": "vocab_mastered",
        "condition_value": 10,
        "category": "vocabulary",
        "rarity": "common",
        "xp_reward": 20,
        "gems_reward": 10,
        "badge_color": "#00BCD4",
        "is_hidden": False,
    },
    {
        "slug": "vocab_builder",
        "name": "Vocab Builder",
        "description": "Master 50 vocabulary words.",
        "condition_type": "vocab_mastered",
        "condition_value": 50,
        "category": "vocabulary",
        "rarity": "rare",
        "xp_reward": 75,
        "gems_reward": 35,
        "badge_color": "#03A9F4",
        "is_hidden": False,
    },
    {
        "slug": "vocab_master",
        "name": "Vocab Master",
        "description": "Master 100 vocabulary words.",
        "condition_type": "vocab_mastered",
        "condition_value": 100,
        "category": "vocabulary",
        "rarity": "epic",
        "xp_reward": 150,
        "gems_reward": 75,
        "badge_color": "#2196F3",
        "is_hidden": False,
    },
    {
        "slug": "walking_dictionary",
        "name": "Walking Dictionary",
        "description": "Master 500 vocabulary words.",
        "condition_type": "vocab_mastered",
        "condition_value": 500,
        "category": "vocabulary",
        "rarity": "legendary",
        "xp_reward": 400,
        "gems_reward": 200,
        "badge_color": "#1976D2",
        "is_hidden": False,
    },
    # XP
    {
        "slug": "xp_hunter",
        "name": "XP Hunter",
        "description": "Earn 500 total XP.",
        "condition_type": "xp_earned",
        "condition_value": 500,
        "category": "xp",
        "rarity": "common",
        "xp_reward": 20,
        "gems_reward": 10,
        "badge_color": "#FFC107",
        "is_hidden": False,
    },
    {
        "slug": "xp_warrior",
        "name": "XP Warrior",
        "description": "Earn 2,000 total XP.",
        "condition_type": "xp_earned",
        "condition_value": 2000,
        "category": "xp",
        "rarity": "rare",
        "xp_reward": 50,
        "gems_reward": 25,
        "badge_color": "#FF9800",
        "is_hidden": False,
    },
    {
        "slug": "xp_champion",
        "name": "XP Champion",
        "description": "Earn 10,000 total XP.",
        "condition_type": "xp_earned",
        "condition_value": 10000,
        "category": "xp",
        "rarity": "epic",
        "xp_reward": 120,
        "gems_reward": 60,
        "badge_color": "#F44336",
        "is_hidden": False,
    },
    {
        "slug": "xp_legend",
        "name": "XP Legend",
        "description": "Earn 50,000 total XP.",
        "condition_type": "xp_earned",
        "condition_value": 50000,
        "category": "xp",
        "rarity": "legendary",
        "xp_reward": 300,
        "gems_reward": 150,
        "badge_color": "#9C27B0",
        "is_hidden": True,
    },
    # Quiz
    {
        "slug": "perfectionist",
        "name": "Perfectionist",
        "description": "Get one perfect quiz score.",
        "condition_type": "perfect_score",
        "condition_value": 1,
        "category": "quiz",
        "rarity": "common",
        "xp_reward": 25,
        "gems_reward": 15,
        "badge_color": "#4CAF50",
        "is_hidden": False,
    },
    {
        "slug": "accuracy_master",
        "name": "Accuracy Master",
        "description": "Get 10 perfect quiz scores.",
        "condition_type": "perfect_score",
        "condition_value": 10,
        "category": "quiz",
        "rarity": "rare",
        "xp_reward": 100,
        "gems_reward": 50,
        "badge_color": "#8BC34A",
        "is_hidden": False,
    },
    {
        "slug": "flawless",
        "name": "Flawless",
        "description": "Get 50 perfect quiz scores.",
        "condition_type": "perfect_score",
        "condition_value": 50,
        "category": "quiz",
        "rarity": "epic",
        "xp_reward": 300,
        "gems_reward": 150,
        "badge_color": "#00BCD4",
        "is_hidden": False,
    },
    {
        "slug": "first_perfect_score",
        "name": "First Perfect",
        "description": "Get 100% on your first quiz attempt.",
        "condition_type": "first_perfect",
        "condition_value": 1,
        "category": "quiz",
        "rarity": "common",
        "xp_reward": 30,
        "gems_reward": 20,
        "badge_color": "#8BC34A",
        "is_hidden": False,
    },
    {
        "slug": "quiz_champion",
        "name": "Quiz Champion",
        "description": "Complete 10 quizzes.",
        "condition_type": "quiz_complete",
        "condition_value": 10,
        "category": "quiz",
        "rarity": "rare",
        "xp_reward": 150,
        "gems_reward": 75,
        "badge_color": "#FFD700",
        "is_hidden": False,
    },
    # Course
    {
        "slug": "course_explorer",
        "name": "Course Explorer",
        "description": "Complete your first course.",
        "condition_type": "course_complete",
        "condition_value": 1,
        "category": "course",
        "rarity": "common",
        "xp_reward": 80,
        "gems_reward": 40,
        "badge_color": "#26A69A",
        "is_hidden": False,
    },
    {
        "slug": "course_champion",
        "name": "Course Champion",
        "description": "Complete 10 courses.",
        "condition_type": "course_complete",
        "condition_value": 10,
        "category": "course",
        "rarity": "legendary",
        "xp_reward": 400,
        "gems_reward": 200,
        "badge_color": "#00796B",
        "is_hidden": False,
    },
    # Voice
    {
        "slug": "voice_beginner",
        "name": "Voice Beginner",
        "description": "Complete 10 voice practice sessions.",
        "condition_type": "voice_practice",
        "condition_value": 10,
        "category": "voice",
        "rarity": "common",
        "xp_reward": 40,
        "gems_reward": 20,
        "badge_color": "#9575CD",
        "is_hidden": False,
    },
    {
        "slug": "voice_talent",
        "name": "Voice Talent",
        "description": "Complete 100 voice practice sessions.",
        "condition_type": "voice_practice",
        "condition_value": 100,
        "category": "voice",
        "rarity": "epic",
        "xp_reward": 250,
        "gems_reward": 120,
        "badge_color": "#7E57C2",
        "is_hidden": False,
    },
    # Level milestones
    {
        "slug": "level_25",
        "name": "Level 25",
        "description": "Reach numeric level 25.",
        "condition_type": "numeric_level",
        "condition_value": 25,
        "category": "level",
        "rarity": "common",
        "xp_reward": 40,
        "gems_reward": 20,
        "badge_color": "#90CAF9",
        "is_hidden": False,
    },
    {
        "slug": "level_50",
        "name": "Level 50",
        "description": "Reach numeric level 50.",
        "condition_type": "numeric_level",
        "condition_value": 50,
        "category": "level",
        "rarity": "rare",
        "xp_reward": 80,
        "gems_reward": 40,
        "badge_color": "#64B5F6",
        "is_hidden": False,
    },
    {
        "slug": "level_100",
        "name": "Level 100",
        "description": "Reach numeric level 100.",
        "condition_type": "numeric_level",
        "condition_value": 100,
        "category": "level",
        "rarity": "epic",
        "xp_reward": 150,
        "gems_reward": 80,
        "badge_color": "#42A5F5",
        "is_hidden": False,
    },
    {
        "slug": "level_150",
        "name": "Level 150",
        "description": "Reach numeric level 150.",
        "condition_type": "numeric_level",
        "condition_value": 150,
        "category": "level",
        "rarity": "epic",
        "xp_reward": 220,
        "gems_reward": 110,
        "badge_color": "#1E88E5",
        "is_hidden": False,
    },
    {
        "slug": "level_200",
        "name": "Level 200",
        "description": "Reach numeric level 200.",
        "condition_type": "numeric_level",
        "condition_value": 200,
        "category": "level",
        "rarity": "legendary",
        "xp_reward": 300,
        "gems_reward": 150,
        "badge_color": "#1976D2",
        "is_hidden": False,
    },
    {
        "slug": "level_300",
        "name": "Level 300",
        "description": "Reach numeric level 300.",
        "condition_type": "numeric_level",
        "condition_value": 300,
        "category": "level",
        "rarity": "legendary",
        "xp_reward": 450,
        "gems_reward": 220,
        "badge_color": "#1565C0",
        "is_hidden": True,
    },
    {
        "slug": "level_500",
        "name": "Immortal",
        "description": "Reach numeric level 500.",
        "condition_type": "numeric_level",
        "condition_value": 500,
        "category": "level",
        "rarity": "legendary",
        "xp_reward": 800,
        "gems_reward": 400,
        "badge_color": "#0D47A1",
        "is_hidden": True,
    },
    # Special (time-based)
    {
        "slug": "night_owl",
        "name": "Night Owl",
        "description": "Study during late-night hours.",
        "condition_type": "study_time_night",
        "condition_value": 1,
        "category": "special",
        "rarity": "rare",
        "xp_reward": 35,
        "gems_reward": 20,
        "badge_color": "#5C6BC0",
        "is_hidden": False,
    },
    {
        "slug": "early_bird",
        "name": "Early Bird",
        "description": "Study during early-morning hours.",
        "condition_type": "study_time_morning",
        "condition_value": 1,
        "category": "special",
        "rarity": "rare",
        "xp_reward": 35,
        "gems_reward": 20,
        "badge_color": "#FFA726",
        "is_hidden": False,
    },
    {
        "slug": "speed_demon",
        "name": "Speed Demon",
        "description": "Complete 5 lessons quickly.",
        "condition_type": "speed_lesson",
        "condition_value": 5,
        "category": "special",
        "rarity": "epic",
        "xp_reward": 100,
        "gems_reward": 50,
        "badge_color": "#EF5350",
        "is_hidden": False,
    },
    # Skill
    {
        "slug": "grammar_guardian",
        "name": "Grammar Guardian",
        "description": "Complete 20 grammar lessons.",
        "condition_type": "grammar_mastered",
        "condition_value": 20,
        "category": "skill",
        "rarity": "epic",
        "xp_reward": 130,
        "gems_reward": 65,
        "badge_color": "#26C6DA",
        "is_hidden": False,
    },
    {
        "slug": "culture_explorer",
        "name": "Culture Explorer",
        "description": "Complete 10 culture lessons.",
        "condition_type": "culture_lesson",
        "condition_value": 10,
        "category": "skill",
        "rarity": "rare",
        "xp_reward": 90,
        "gems_reward": 45,
        "badge_color": "#AB47BC",
        "is_hidden": False,
    },
    {
        "slug": "writing_wizard",
        "name": "Writing Wizard",
        "description": "Complete 20 writing lessons.",
        "condition_type": "writing_complete",
        "condition_value": 20,
        "category": "skill",
        "rarity": "epic",
        "xp_reward": 130,
        "gems_reward": 65,
        "badge_color": "#26A69A",
        "is_hidden": False,
    },
    {
        "slug": "listening_legend",
        "name": "Listening Legend",
        "description": "Complete 50 listening lessons.",
        "condition_type": "listening_complete",
        "condition_value": 50,
        "category": "skill",
        "rarity": "legendary",
        "xp_reward": 260,
        "gems_reward": 130,
        "badge_color": "#5E35B1",
        "is_hidden": False,
    },
    # Social
    {
        "slug": "social_butterfly",
        "name": "Social Butterfly",
        "description": "Complete 5 social interactions.",
        "condition_type": "social_interaction",
        "condition_value": 5,
        "category": "social",
        "rarity": "rare",
        "xp_reward": 60,
        "gems_reward": 30,
        "badge_color": "#29B6F6",
        "is_hidden": False,
    },
    {
        "slug": "conversation_champion",
        "name": "Conversation Champion",
        "description": "Complete 20 chat sessions.",
        "condition_type": "chat_complete",
        "condition_value": 20,
        "category": "social",
        "rarity": "epic",
        "xp_reward": 140,
        "gems_reward": 70,
        "badge_color": "#42A5F5",
        "is_hidden": False,
    },
    {
        "slug": "feedback_friend",
        "name": "Feedback Friend",
        "description": "Help others 10 times.",
        "condition_type": "help_others",
        "condition_value": 10,
        "category": "social",
        "rarity": "rare",
        "xp_reward": 100,
        "gems_reward": 50,
        "badge_color": "#26A69A",
        "is_hidden": False,
    },
    # Milestones
    {
        "slug": "challenge_crusher",
        "name": "Challenge Crusher",
        "description": "Complete 10 daily challenges.",
        "condition_type": "daily_challenge_complete",
        "condition_value": 10,
        "category": "milestone",
        "rarity": "epic",
        "xp_reward": 160,
        "gems_reward": 80,
        "badge_color": "#FF7043",
        "is_hidden": False,
    },
    {
        "slug": "milestone_maker",
        "name": "Milestone Maker",
        "description": "Complete 50 daily challenges.",
        "condition_type": "daily_challenge_complete",
        "condition_value": 50,
        "category": "milestone",
        "rarity": "legendary",
        "xp_reward": 350,
        "gems_reward": 175,
        "badge_color": "#F4511E",
        "is_hidden": False,
    },
    {
        "slug": "comeback_king",
        "name": "Comeback King",
        "description": "Return after a break and complete a lesson.",
        "condition_type": "comeback",
        "condition_value": 1,
        "category": "milestone",
        "rarity": "rare",
        "xp_reward": 60,
        "gems_reward": 30,
        "badge_color": "#8D6E63",
        "is_hidden": True,
    },
]


async def seed_achievements() -> None:
    created = 0
    updated = 0

    async with AsyncSessionLocal() as db:
        for item in ACHIEVEMENT_SEED:
            slug = item["slug"]
            payload = {
                **item,
                "badge_icon": _cdn_badge_icon(slug),
            }

            existing = await db.scalar(
                select(Achievement).where(Achievement.slug == slug)
            )

            if existing is None:
                # Backward compatibility for legacy rows seeded without slug.
                existing = await db.scalar(
                    select(Achievement).where(Achievement.name == item["name"])
                )

            if existing is None:
                db.add(Achievement(**payload))
                created += 1
                continue

            row_changed = False
            for key, value in payload.items():
                if getattr(existing, key) != value:
                    setattr(existing, key, value)
                    row_changed = True

            if row_changed:
                updated += 1

        await db.commit()

        total = await db.scalar(select(func.count(Achievement.id))) or 0
        with_slug = await db.scalar(
            select(func.count(Achievement.id)).where(Achievement.slug.is_not(None))
        ) or 0
        with_badge_icon = await db.scalar(
            select(func.count(Achievement.id)).where(Achievement.badge_icon.is_not(None))
        ) or 0

    print("ACHIEVEMENT_SEED_DONE")
    print(f"created={created}")
    print(f"updated={updated}")
    print(f"total={total}")
    print(f"with_slug={with_slug}")
    print(f"with_badge_icon={with_badge_icon}")


if __name__ == "__main__":
    asyncio.run(seed_achievements())
