server {
    listen 443 ssl http2;
    server_name ${API_SERVER_NAME};

    ssl_certificate ${API_SSL_CERT_PATH};
    ssl_certificate_key ${API_SSL_KEY_PATH};

    client_max_body_size 25m;

    location / {
        proxy_pass http://<PRIVATE_IP_BACKEND>:8000;
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_connect_timeout 15s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}

server {
    listen 443 ssl http2;
    server_name ${AI_SERVER_NAME};

    ssl_certificate ${AI_SSL_CERT_PATH};
    ssl_certificate_key ${AI_SSL_KEY_PATH};

    client_max_body_size 25m;

    location / {
        proxy_pass http://<PRIVATE_IP_AI>:8001;
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_connect_timeout 30s;
        proxy_send_timeout 180s;
        proxy_read_timeout 180s;
    }
}
